import JSZip from 'jszip';
import { jsPDF } from 'jspdf';

export const downloadPNG = (canvas: HTMLCanvasElement, filename: string) => {
  const link = document.createElement('a');
  link.download = `${filename}.png`;
  link.href = canvas.toDataURL('image/png', 1.0);
  link.click();
};

export const downloadSVG = (svg: SVGSVGElement, filename: string) => {
  const svgData = new XMLSerializer().serializeToString(svg);
  const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
  const svgUrl = URL.createObjectURL(svgBlob);
  const link = document.createElement('a');
  link.download = `${filename}.svg`;
  link.href = svgUrl;
  link.click();
};

export const downloadPDF = async (canvas: HTMLCanvasElement, filename: string) => {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });
  
  // Use maximum quality PNG data from the high-res canvas
  const imgData = canvas.toDataURL('image/png', 1.0);
  const qrSize = 120; // 120mm for print quality
  const x = (210 - qrSize) / 2;
  const y = (297 - qrSize) / 2;
  
  // The canvas is already 1024px which maps well to print at 120mm (~216 DPI)
  pdf.addImage(imgData, 'PNG', x, y, qrSize, qrSize);
  pdf.setFontSize(10);
  pdf.setTextColor(150, 150, 150);
  pdf.text('Generated by Velagio QR Studio', 105, y + qrSize + 15, { align: 'center' });
  pdf.save(`${filename}.pdf`);
};

export const downloadBulkZIP = async (qrElements: { url: string; canvas: HTMLCanvasElement }[], zipName: string) => {
  const zip = new JSZip();
  const folder = zip.folder('qr_codes');
  
  qrElements.forEach((item, index) => {
    const dataUrl = item.canvas.toDataURL('image/png').split(',')[1];
    const safeUrl = item.url.replace(/[^a-z0-9]/gi, '_').toLowerCase().slice(0, 30);
    folder?.file(`${index + 1}_${safeUrl}.png`, dataUrl, { base64: true });
  });
  
  const content = await zip.generateAsync({ type: 'blob' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(content);
  link.download = `${zipName}.zip`;
  link.click();
};
